events {}
http {
  server {
    listen 8080;

    location = /admin/health {
      default_type application/json;
      alias /etc/nginx/cert-status/cert-status;
    }

    location / {
      return 404;
    }
  }
}
